version: "3.8"
services:
  db:
    container_name: chronotrains_postgis
    image: postgis/postgis
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "33011:5432"
    volumes:
      - /mnt/data/configs/chronotrains_postgis:/var/lib/postgresql/data
